### ISSUE TITLE
Hide when nothing is happening...

### ISSUE THREAD

**Issue by Snille** [derekn/MMM-TautulliActivity#1]
Hi! I just recently found your module. :)
I'm thinking of adding it to my setup. However, I think maybe it would be a good option to be able to set the module to hide it self when nothing is being "watched". I have other modules doing this. :)

Thank you!

**Comment by derekn** [comment]
Great suggestion! I have added this as an option "hideOnNoActivity": true will now hide the widget when there is nothing being played.

**Comment by Snille** [comment]
Thank you! Works great! :)
