### ISSUE TITLE
just says loading

### ISSUE THREAD

**Issue by ausheikh** [derekn/MMM-TautulliActivity#2]
I cant seem to get the widget to work, it just says loading...
do i have to use https to connect to the tautulli server?

**Comment by derekn** [comment]
It will continue to say "loading" if it cannot establish a connection to Tautulli. Normally you should have the host string using HTTPS, but this depends on your setup. Try changing it and letting me know if that fixes it for you

**Comment by ausheikh** [comment]
i tried both, using just http and https, both had the same result

**Comment by derekn** [comment]
try using the IP address and making sure the magicmirror can access the tautulli server directly. also you can check the magicmirror logs for errors.

**Comment by ausheikh** [comment]
working now, thanks
