### ISSUE TITLE
"there was an error"

### ISSUE THREAD

**Issue by XoniBlue** [derekn/MMM-TautulliActivity#3]
api and host are set correctly, double verfied both, using http not https. in red text it shows there was an error.

**Comment by derekn** [comment]
that indicates it did not receive a valid response from tautulli, what is the specific error in the MM console log?

**Comment by XoniBlue** [comment]
tbh ive got no idea where to look for that.

**Comment by derekn** [comment]
it's in the console where you run MM from, or in pm2 logs if you run it with pm2

**Comment by XoniBlue** [comment]
no errors found. i added /home to the end of the url as it shows when i open tautulli, this changed the "there was an error" to  "loading" but still no data is parsing.

**Comment by XoniBlue** [comment]
jk heres some logs.  

0|mm       | [2020-10-29 00:43:29.387] [ERROR]  Whoops! There was an uncaught exception...
0|mm       | [2020-10-29 00:43:29.389] [ERROR]  SyntaxError: Unexpected token u in JSON at position 0
0|mm       |     at JSON.parse (<anonymous>)
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-TautulliActivity/node_helper.js:12:20)
0|mm       |     at self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|mm       |     at Request.emit (events.js:200:13)
0|mm       |     at Request.init (/home/pi/MagicMirror/node_modules/request/request.js:458:17)
0|mm       |     at new Request (/home/pi/MagicMirror/node_modules/request/request.js:127:8)
0|mm       |     at request (/home/pi/MagicMirror/node_modules/request/index.js:53:10)
0|mm       |     at /home/pi/MagicMirror/node_modules/request/index.js:61:12
0|mm       |     at Function.get (/home/pi/MagicMirror/node_modules/request/index.js:100:12)
0|mm       |     at Class.getData (/home/pi/MagicMirror/modules/MMM-TautulliActivity/node_helper.js:11:7)

**Comment by XoniBlue** [comment]
needed to fetch new token within tautulli, adding the /home was incorrect, my initial settings were indeed correct. the problem existed on tautullis' side.
