### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by NederWeb** [derekn/MMM-TautulliActivity#4]
I'm getting this error:

MMM-TautulliActivity: FetchError: request to https://xxx:32500/api/v2?apikey=xxx&cmd=get_activity failed, reason: self signed certificate

Is there a way around this?

(Without disabling https, or not using a non self signed cert)

**Comment by derekn** [comment]
I just committed a fix for self-signed certificates, pull the latest version and let me know if that fixes it for you.

**Comment by NederWeb** [comment]
Hello, it does work now. Thank you.
