### ISSUE TITLE
Modified version of this?

### ISSUE THREAD

**Issue by cruzanhtpc** [derekn/MMM-TautulliActivity#5]
would you happen to know if it is easy to modify your module to make a  recently added from Tautulli,  ie  last 5 recently added Movies , last 5 tv show episodes,  

with the config of x amount to display or hide either tv or movie. 

Just a thought, im searching to see if there is a module like that but have only found yours so far.

**Comment by derekn** [comment]
that is outside the scope of this project, but yes it is very possible and would be fairly simple to do. recently added is available from the Tautulli api, so would just be a matter of formatting and displaying it.
