### ISSUE TITLE
HTTP API not working...

### ISSUE THREAD

**Issue by Snille** [derekn/MMM-TautulliActivity#6]
Hi, I'm trying to use the API (locally), so I don't have Tautulli setup with https.
But when I try to use http://IP on "host" it only says: `MMM-TautulliActivity: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"`
Is there anyway you can make it work with http as well? 

Thank you! :)

**Comment by derekn** [comment]
This should be fixed now with the latest commit

**Comment by Snille** [comment]
Thank you! It's working! :)
